### PR TITLE
Update getmeta.js

### PR DESCRIPTION
**Pull request by jangatzke**
See https://github.com/ioBroker/ioBroker.mysensors/issues/1

### CODE REVIEW

**Comment by GermanBluefox** [comment]
I have no mysensors and I cant check this pull request. 
What exactly was changed?
Where can I find the description for S_SCENE_CONTROLLER / V_SCENE_ON / V_SCENE_OFF  ?

**Comment by jangatzke** [comment]
You can find some info in the API description:
https://www.mysensors.org/download/serial_api_20
However this does not include the actual data type. 
https://www.mysensors.org/build/scene_controller includes an example sketch. Here are the important lines:
` int pressedButton = myButtons.checkButtons();`
.
.
.
`send(off.set(pressedButton));`

The sent value is clearly not a bool for on/off. The data type V_SCENE_ON/OFF carries the on/off command. It's value is the actual scene which should be controlled. I hope it is getting clear now. :)

The Update to main.js sets the ack flag to true for all outgoing commands. If the ack flag is not set to true, the nodes will never send an ack. I have tested it, the ack flag of the state gets set to true only, when the node is alive. Without the change the ack flag of the state in iobroker was always false. See the MySensors API documentation here:

https://www.mysensors.org/download/serial_api_20

> The ack parameter has the following meaning: Outgoing: 0 = unacknowledged message, 1 = request ack from destination node, Incoming: 0 = normal message, 1 = this is an ack message

My very own testing shows those change do not seem to break anything. But I must admit, that this is my first time editing js code and my first steps on github, too. So we better have it double checked.

**Comment by Apollon77** [comment]
My idea would be to accept it, create new version and create a test thread in forum before publishing it.
@GermanBluefox What you think?

**Comment by GermanBluefox** [comment]
Sounds resonable.

23 окт. 2017 г. 23:06 пользователь "Ingo Fischer" <notifications@github.com>
написал:

**Comment by Apollon77** [comment]
@jangatzke if you can prepare new version it would be faster :-)
increase version in package.json/io-package.json incl. new entry in io-package and README.md :-) Put your name in the news :-)
I'm not on my laptop so I could not do before tomorrow ...

**Comment by jangatzke** [comment]
@Apollon77 I have created a new Version and updated the pull request.

**Comment by Apollon77** [comment]
Perfect.
Testing Thread in Forum: http://forum.iobroker.net/viewtopic.php?f=36&t=8653

**Pull request merged**
