### PR TITLE
New version lib 2.3.x and support sleeping node

### PR DESCRIPTION
**Pull request by Haba1234**
Added new objects (library 2.3.x) 
Added support for sleeping nodes 
changed "sensors": "^1.1.1" (Pull request geek/sensors#6)

### CODE REVIEW

**Comment by Apollon77** [comment]
According to test results (see https://travis-ci.org/ioBroker/ioBroker.mysensors/jobs/429653097) sensory@1.1.1 does not exist on npm!

**Comment by Haba1234** [comment]
The developer has not yet accepted Pull request

**Comment by Apollon77** [comment]
Then we need to wait for this :-( maybe link it here?

**Comment by Haba1234** [comment]
how?

**Comment by Apollon77** [comment]
Post link of Your PR here

**Comment by Haba1234** [comment]
higher was :)
changed "sensors": "^1.1.1" (Pull request )  [https://github.com/geek/sensors/pull/6](url)
fork [https://github.com/Haba1234/sensors](url)

**Comment by Apollon77** [comment]
I'm not sure if someone will consider the PR when you also break the tests there: https://travis-ci.org/geek/sensors/jobs/428705417 ;-)

**Comment by Apollon77** [comment]
Alterative wuld be to replace the dependecy to a github repo .. but then users need to have git installed to install the adapter

**Comment by GermanBluefox** [comment]
> but then users need to have git installed to install the adapter

You can always use tarball. It requires no git. https://github.com/Haba1234/sensors/tarball/a751633505706e980a03eb176177d5671ba9ff58

**Comment by Haba1234** [comment]
> I'm not sure if someone will consider the PR when you also break the tests there

I fixed the tests :)

**Comment by Apollon77** [comment]
hehe, I meaned the tests at "sensors" library :-) not iobroker ...

**Comment by Haba1234** [comment]
Yes! [https://github.com/geek/sensors/pull/6](url)
I did not understand how to fix the tests in iobroker :(

**Comment by GermanBluefox** [comment]
May be create sensors2. While last commit for sensors is on 5 Jul 2016....

**Comment by GermanBluefox** [comment]
The PR is merged now! @Haba1234 can you continue?

**Comment by Haba1234** [comment]
yes!

**Comment by Haba1234** [comment]
done?

**Pull request merged**
