### PR TITLE
Update for Admin v3

### PR DESCRIPTION
**Pull request by Haba1234**

### CODE REVIEW

**Comment by Haba1234** [comment]
There is an unsolved problem.
socket.emit ('getState', adapter + '.' + instance + '.inclusionOn', function (err, state)
caches the value at the first start and does not update.

**Comment by GermanBluefox** [comment]
> There is an unsolved problem.
socket.emit ('getState', adapter + '.' + instance + '.inclusionOn', function (err, state)
caches the value at the first start and does not update.

Update during the configuration dialog is opened or really never?

**Comment by Haba1234** [comment]
Actually never. SetState command is executed correctly, and GetState command returns the correct value only once. In the future, only this value is returned.

**Comment by GermanBluefox** [comment]
Try to subscribe this value in config.

20 февр. 2018 г. 10:08 пользователь "Haba1234" <notifications@github.com>
написал:

**Pull request merged**
